
# @id = 78ioio89
Post http://localhost:3003/nova-obra
Content-Type: application/json

{
    "nome_obra":"Ed. Gustavinho" ,
    "qty_andares":"2" ,
    "qty_ap_andar":"3" ,
    "responsavel":"Priscilla e Thiago" 
}

###
@id = '12EIE12'
DELETE http://localhost:3003/obra/{{id}}

###

@id = '726e40b3-bfa6-4dd9-958d-cc8929d04931'
get  http://localhost:3003/construction/info/{{id}}
Content-Type: application/json

{
    "token" : "726e40b3-bfa6-4dd9-958d-cc8929d04931"
}

###
@id = '45231oaifdhaof'
DELETE   http://localhost:3003/apartamento/delete/{{id}}
Content-Type: application/json

###
@id = 'f78bdc48-029b-492b-afa1-1d41b64566f1'
GET   http://localhost:3003/info/{{id}}
Content-Type: application/json


###
Post http://localhost:3003/user/signup
Content-Type: application/json

{
    "name": "Priscilla",
    "email": "pri@hirt.com",
    "password": "123456789",
    "role": "collab"  
}

###
@id = 726e40b3-bfa6-4dd9-958d-cc8929d04931
put http://localhost:3003/construction/editConstruction/{{id}}
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRlOTcyZTUwLWU0NTAtNGU0OC05NDg3LWRjZGJlYTU5MDZjNCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY3NzcxMTcwNSwiZXhwIjoxNjc3NzEzNTA1fQ.kG8mNevNIS2boi9yf9HUAB1WWRgixUfnM8rvP4jdl8c

{
    "nome_obra": "Ed Priscilla",
    "qty_andares": "",
    "qty_ap_andar": "",
    "responsavel": ""  
}